name: Deploy ASP.NET Core Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List root directory after checkout
        run: ls -R /home/runner/work/WhoKnows-backend/WhoKnows-backend

      - name: List specific directory for debugging
        run: ls -R "/home/runner/work/WhoKnows-backend/WhoKnows-backend/Whoknows backend"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Build Backend
        working-directory: "/home/runner/work/WhoKnows-backend/WhoKnows-backend/Whoknows backend" # Update based on the correct path
        run: dotnet publish -c Release -o ./publish

      - name: Deploy Backend to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          source: "/home/runner/work/WhoKnows-backend/WhoKnows-backend/Whoknows backend/publish/*" # Update path if needed
          target: ${{ secrets.VM_BACKEND_DIR }}

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          script: |
            sudo systemctl restart backend.service