# name: Deploy .NET API to Remote VM
name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-api
          path: ./publish

      - name: Deploy to remote VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key for authentication
        run: |
          # Ensure correct formatting of SSH key and remove Windows line endings
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
          chmod 600 key.pem

          # SSH into the remote VM and remove old files
          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@40.87.131.145 << 'EOF'
            rm -rf /Backend/publish/*
            echo "Old files deleted from /Backend/publish"
          EOF

          # Copy the new publish folder to the remote VM
          scp -i key.pem -o StrictHostKeyChecking=no -r ./publish azureuser@40.87.131.145:/Backend/

          # Start the .NET application on the remote server
          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@40.87.131.145 << 'EOF'
            cd /Backend/publish/
            dotnet "Whoknows backend.dll" & 
            echo "Application started successfully"
          EOF

      # Cleanup SSH key file after use
      - name: Cleanup
        run: rm -f key.pem

      - name: Run EF Core Migrations
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # SSH private key for authentication
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@40.87.131.145 << 'EOF'
            cd /Backend
            dotnet "Whoknows backend.dll" database update # Run migrations here
          EOF