name: Deploy ASP.NET Core Backend

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x" # Use the appropriate .NET version

      - name: Build Backend
        working-directory: "./Whoknows backend" # Change to your ASP.NET Core project directory
        run: dotnet publish -c Release -o ./publish

      - name: Deploy Backend to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          source: "./Whoknows backend/publish/*
          target: ${{ secrets.VM_BACKEND_DIR }}

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          script: |
            # Commands to restart your backend service
            sudo systemctl restart backend.service
