name: Deploy dotnet API Gateway Backend to Remote VM

on:
  push:
    branches:
      - feature/createYml

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project (Frontend & Backend)
        run: dotnet build --configuration Release

      - name: Publish the web API backend
        run: dotnet publish --configuration Release --output ./publish

      # Check if publish folder exists and list its contents (for debugging)
      - name: List published files
        run: ls -al ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-backend
          path: ./publish

      - name: Deploy to remote VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Write the SSH key to a file
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@40.87.131.145 << 'EOF'
            rm -rf /Backend/publish/*
            echo "Old files deleted from /Backend/publish/"
          EOF

          scp -i key.pem -o StrictHostKeyChecking=no -r ./publish azureuser@40.87.131.145:Backend/

          ssh -i key.pem -o StrictHostKeyChecking=no azureuser@40.87.131.145 << 'EOF'
            cd Backend/publish/
            dotnet "WhoKnows backend.dll" &
            echo "Application started successfully"
          EOF

      # Cleanup SSH key file after use
      - name: Cleanup
        run: rm -f key.pem
