name: Deploy ASP.NET Core Backend

on:
  push:
    branches:
      - main # Change to the branch you want to deploy from

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.401" # Use the appropriate .NET version

      - name: Build Backend
        working-directory: ./AspNetCoreProject # Change to your ASP.NET Core project directory
        run: dotnet publish -c Release -o ./publish

      - name: Deploy Backend to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "./AspNetCoreProject/publish/*"
          target: ${{ secrets.AZURE_VM_BACKEND_DIR }}

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            # Commands to restart your backend service
            sudo systemctl restart backend.service
